FROM ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlex/paddlex:paddlex3.3.4-paddlepaddle3.2.0-gpu-cuda11.8-cudnn8.9-trt8.6


RUN python -m pip install "paddleocr[all]==3.3.2"

RUN paddlex --install serving
